apiVersion: v1
kind: Service
metadata:
  name: nginx-sts01
  labels:
    app: nginx-sts01
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-sts01
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx-sts01"
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sts01
  template:
    metadata:
      labels:
        app: nginx-sts01
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
          name: web




#  dig +short web-0.nginx-sts01.default.svc.cluster.local @10.96.0.10
