apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    name: pv001
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # 回收策略,pvc解除绑定触发     Recycle、Retain、Delete
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /data/volumes/v1
    server: store1
