kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephrbd-sc
  namespace: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ceph.com/rbd
reclaimPolicy: Retain
parameters:
  monitors: 10.0.12.95:6789 # ceph-server-ip
  adminId: admin
  adminSecretName: storage-secret
  adminSecretNamespace: default
  pool: cephrbd
  fsType: xfs
  userId: admin
  userSecretName: storage-secret
  imageFormat: "2"
