apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  # namespace: ingress-nginx
  labels:
    app: myapp-rs
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
      release: canary
      env: qa
  template:
    metadata:
      name: myapp-pod
      labels:
        app: nginx
        release: canary
        env: qa
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80 # 容器端口
              name: http
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
#  pod*3 + rs
#  rs 会替换pod的名字 spec.template.metadata.name 不生效
---
kind: Service
apiVersion: v1
metadata:
  # namespace: ingress-nginx
  name: nginx
spec:
  type: NodePort
  ports:
    - name: nginx
      port: 8001
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
