apiVersion: v1
kind: Pod
metadata:
  name: nginx-po
  labels:
    app: nginx-po
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: nginx-po
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
