apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  port: "80"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - name: http
          containerPort: 80
      env:
        - name: NGINX_PORT
          valueFrom:
            configMapKeyRef:
              key: nginx-configmap
              name: port
              # optional: true
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

  volumes:
    - name: cfg
      items:
