apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
stringData:
  password: "123456"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo-cm
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - name: http
          containerPort: 80
      env:
        - name: xx
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: password
              # 不会实时更新
      volumeMounts:
        - mountPath: /etc/nginx/config.d/
          # /etc/nginx/config.d/password_file
          # 以 Volume 方式使用的 Secret 支持动态更新：Secret 更新后，容器中的数据也会更新。
          name: nginx-secret
          # 会同步过来
          # 会将cm的每个key当成一个文件写到磁盘上
          readOnly: true
  volumes:
    - name: nginx-secret
      secret:
        secretName: nginx-secret
        items:
          - key: password
            path: password_file
            mode: 0777
