version: '3'
services:
  log-gen:
    build: log-gen/
    container_name: log-gen
    depends_on:
      - filebeat
    volumes:
      - ./log:/app/log
  #  fluentd:
  #    build: ./fluentd/
  #    container_name: fluentd
  #    volumes:
  #      - ./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf
  #      - ./log/:/fluentd/log
  #      - ./log:/app/log
  #    environment:
  #      - FLUENTD_CONF=fluentd.conf
  #    depends_on:
  #      - elasticsearch
  #      - kibana
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.4.1
    volumes:
      - ./log:/var/log:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
      - kibana
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - transport.host=127.0.0.1

  kibana:
    container_name: kibana
    image: kibana:7.6.2
    environment:
      SERVER_NAME: kibana-server
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
