apiVersion: v1
kind: Pod
metadata:
  namespace: mesoid
  name: efk
  labels:
    name: efk
spec:
  imagePullSecrets:
    - name: myregistrykey
  containers:
    - name: log-gen
      image: harbor.ls.com/lie/log-gen:v1
      volumeMounts:
        - mountPath: /app/log
          name: log
    - name: log-collection
      image: docker.elastic.co/beats/filebeat:7.4.1
      volumeMounts:
        - mountPath: /usr/share/filebeat/cfg
          name: filebeat
        - mountPath: /app/log
          name: log
      securityContext:
        runAsUser: 0
      lifecycle:
        postStart:
          exec:
            command: [ "/bin/sh", "-c", "cp /usr/share/filebeat/cfg/filebeat.yml /usr/share/filebeat/filebeat.yml" ]
  volumes:
    - name: log
      emptyDir: {}
    - name: filebeat
      configMap:
        name: filebeat
        items:
          - key: conf
            path: "./filebeat.yml"
