kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: nfs
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate #---设置升级策略为删除再创建(默认为滚动更新)
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          # image: quay.mirrors.ustc.edu.cn/external_storage/nfs-client-provisioner:latest
          image: vbouchaud/nfs-client-provisioner:latest@sha256:7a3ce14ff7cb388a70d7f7c89d60d899852dc2c68ac03a29f8556cc8bed0657f
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-client #--- nfs-provisioner的名称，以后设置的storageclass要和这个保持一致
            - name: NFS_SERVER
              value: 192.168.33.9 #---NFS服务器地址，和 valumes 保持一致
            - name: NFS_PATH
              value: /nfs #---NFS服务器目录，和 valumes 保持一致
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.33.9 #---NFS服务器地址
            path: /nfs #---NFS服务器目录
