apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-nacos
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql-nacos # has to match .spec.template.metadata.labels
  serviceName: "mysql-nacos"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mysql-nacos # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: mysql-nacos
          image: nacos/nacos-mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "nacos_devtest"
            - name: MYSQL_USER
              value: "nacos"
            - name: MYSQL_PASSWORD
              value: "nacos"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-nacos

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-nacos
spec:
  storageClassName: nfs-storage #---需要与上面创建的storageclass的名称一致
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-nacos
  labels:
    name: mysql-nacos
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-nacos
