apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: "nginx"
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - name: http
              containerPort: 80

        - name: dnsutils
          image: mydlqclub/dnsutils:1.3
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "ping 127.0.0.1"]
        - name: centos
          image: centos:7
          command: ["/bin/sh", "-c", "ping 127.0.0.1"]
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  # type: NodePort
  type: LoadBalancer
