apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: myapp-svc
spec:
  selector:
    app: myapp-pod
  ports:
    - port: 80
      name: web
      # targetPort: <Target Port>
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp-pod
  serviceName: myapp-svc
  # 必须是无头服务,才能给每个pod一个唯一的标识符
  replicas: 5
  template:
    metadata:
      labels:
        app: myapp-pod
    spec:
      containers:
        # nslookup myapp-2.myapp-svc
        # Name:      myapp-0
        # Address 1: 100.117.144.137 myapp-0.myapp-svc.default.svc.cluster.local
        # dig -t A myapp-1.myapp.default.svc.cluster.local @100.85.170.130
        - name: myapp
          image: ikubernetes/myapp:v1
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: myappdata
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    # 动态请求创建pvc
    - metadata:
        name: myappdata
      spec:
        accessModes: ["ReadWriteOnce"]
        # storageClassName: "gluster-dynamic"
        resources:
          requests:
            storage: 1Gi
