kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
  # 系统默认存在
subjects:
  - kind: ServiceAccount
    name: heapster
    namespace: kube-system
