apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  # storageClassName: nfs-storageclass
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      name: pv001
  # volumeMode:
  # volumeName:
