kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod
      image: centos:7
      command:
        - sleep
        - "36000"
      volumeMounts:
        - name: test-pod
          mountPath: "/mnt"
  volumes:
    - name: test-pod
      persistentVolumeClaim:
        claimName: test-pod
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pod
spec:
  storageClassName: nfs-storage #---需要与上面创建的storageclass的名称一致
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
