name: Script

on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  build:
    runs-on: centos
    steps:
    - name: 'sed-'
      run: sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
    - name: 'sed'
      run: sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    - name: 'makecache'
      run: yum makecache 
    - name: 'update'
      run: yum update -y 
    - name: 'install'
      run: yum -y install vim wget unzip skopeo -y
    - name: 'login'
      run: skopeo login -u 15733101139 registry.cn-hangzhou.aliyuncs.com -p ${PASSWORD}
    - name: sync
      run: skopeo sync --src docker --dest docker kindest/node registry.cn-hangzhou.aliyuncs.com/acejilam --src-tls-verify=false --dest-tls-verify=false 
 
