name: Script

on:
  schedule:
    - cron: '*/1 * * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
 #   - name: 'sed-'
 #     run: sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
 #   - name: 'sed'
 #     run: sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
 #   - name: 'makecache'
 #     run: yum makecache 
    - name: 'update'
      run: sudo apt update 
    - name: 'install'
      run: sudo apt -y install vim wget unzip skopeo 
    - name: 'login'
      run: skopeo login -u 15733101139 registry.cn-hangzhou.aliyuncs.com -p "$env:SUPER_SECRET"
      env:
        SUPER_SECRET: ${{ secrets.PASSWORD }}
    - name: sync
      run: skopeo sync --src docker --dest docker kindest/node registry.cn-hangzhou.aliyuncs.com/acejilam --src-tls-verify=false --dest-tls-verify=false 
 
