name: golang
on:
  schedule:
    - cron: '*/1 * * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'update'
      run: sudo apt update
    - name: 'install'
      run: sudo apt -y install vim wget unzip skopeo
    - name: 'login'
      run: skopeo login -u ${{ secrets.REGISTERY_USERNAME }} registry.cn-hangzhou.aliyuncs.com -p "${{ secrets.REGISTERY_PASSWORD }}"
    - name: sync
      run: skopeo sync --src docker --dest docker golang registry.cn-hangzhou.aliyuncs.com/acejilam --src-tls-verify=false --dest-tls-verify=false

